// Exports
export * from './roles';
export * from './schedules';
export * from './banks';
export * from './religions';
export * from './users';
export * from './companies';
export * from './employees';
export * from './employee-salaries';
export * from './task-comments';
export * from './user-profiles';
export * from './positions';
export * from './schools';
export * from './shifts';
export * from './units';
export * from './shift-schedules';
export * from './presences';
export * from './stages';
export * from './password-reset-tokens';
export * from './sessions';
export * from './documents';
export * from './settings';
export * from './clients';
export * from './projects';
export * from './project-users';
export * from './project-columns';
export * from './tasks';
export * from './task-activities';
export * from './pages';
export * from './activity-logs';
export * from './news';
export * from './tags';
export * from './taggables';
export * from './notifications';
export * from './push-subscriptions';
export * from './attachments';
export * from './comments';
export * from './contacts';
export * from './newsletter-subscriptions';
export * from './jobs';
export * from './job-applicants';
export * from './invoices';
export * from './expenses';
export * from './timesheets';
export * from './leave-requests';
export * from './permissions';
export * from './role-permissions';
export * from './user-permissions';
export * from './services';
export * from './payrolls';
export * from './payroll-payment-logs';
export * from './salary-components';
export * from './audit-logs';
export * from './devices';
export * from './accounting/accounts';
export * from './accounting/journals';
export * from './accounting/entries';
export * from './inventory/warehouses';
export * from './inventory/products';
export * from './inventory/stock';
export * from './crm/leads';
export * from './crm/orders';
export * from './purchase/orders';
export * from './purchase/requisitions';
export * from './announcements';
export * from './announcement-recipients';
export * from './categories';
export * from './categorizables';

import { roles } from './roles';
import { users } from './users';
import { jobs } from './jobs';
import { jobApplicants } from './job-applicants';
import { passwordResetTokens } from './password-reset-tokens';
import { sessions } from './sessions';
import { documents } from './documents';
import { settings } from './settings';
import { tasks } from './tasks';
import { taskActivities } from './task-activities';
import { projects } from './projects';
import { projectUsers } from './project-users';
import { projectColumns } from './project-columns';
import { clients } from './clients';
import { pages } from './pages';
import { news } from './news';
import { activityLogs } from './activity-logs';
import { notifications } from './notifications';
import { pushSubscriptions } from './push-subscriptions';
import { attachments } from './attachments';
import { comments } from './comments';
import { tags } from './tags';
import { taggables } from './taggables';
import { contacts } from './contacts';
import { newsletterSubscriptions } from './newsletter-subscriptions';
import { userProfiles } from './user-profiles';
import { banks } from './banks';
import { positions } from './positions';
import { religions } from './religions';
import { schools } from './schools';
import { shifts } from './shifts';
import { stages } from './stages';
import { units } from './units';
import { invoices, invoiceItems, invoicePayments } from './invoices';
import { expenses } from './expenses';
import { timesheets } from './timesheets';
import { leaveRequests } from './leave-requests';
import { permissions } from './permissions';
import { rolePermissions } from './role-permissions';
import { userPermissions } from './user-permissions';
import { companies } from './companies';
import { employees } from './employees';
import { shiftSchedules } from './shift-schedules';
import { presences } from './presences';
import { employeeSalaries } from './employee-salaries';
import { payrollBatches, payrolls } from './payrolls';
import { payrollPaymentLogs } from './payroll-payment-logs';
import { salaryComponents, employeeSalaryComponents } from './salary-components';
import { devices } from './devices';
import { services } from './services';
import { accounts } from './accounting/accounts';
import { journals } from './accounting/journals';
import { journalEntries, journalItems } from './accounting/entries';
import { warehouses, locations } from './inventory/warehouses';
import { products, productCategories } from './inventory/products';
import { stockMoves, stockQuants } from './inventory/stock';
import { leads } from './crm/leads';
import { salesOrders, salesOrderLines } from './crm/orders';
import { purchaseOrders, purchaseOrderLines } from './purchase/orders';
import { purchaseRequisitions, purchaseRequisitionLines } from './purchase/requisitions';
import { announcements } from './announcements';
import { announcementRecipients } from './announcement-recipients';
import { schedules } from './schedules';
import { categories } from './categories';
import { categorizables } from './categorizables';

export type Role = typeof roles.$inferSelect;
export type NewRole = typeof roles.$inferInsert;
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;
export type Document = typeof documents.$inferSelect;
export type Setting = typeof settings.$inferSelect;
export type NewSetting = typeof settings.$inferInsert;
export type Task = typeof tasks.$inferSelect;
export type NewTask = typeof tasks.$inferInsert;
export type Project = typeof projects.$inferSelect;
export type ProjectUser = typeof projectUsers.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type Page = typeof pages.$inferSelect;
export type News = typeof news.$inferSelect;
export type NewNews = typeof news.$inferInsert;
export type ActivityLog = typeof activityLogs.$inferSelect;
export type NewActivityLog = typeof activityLogs.$inferInsert;
export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;
export type PushSubscription = typeof pushSubscriptions.$inferSelect;
export type Attachment = typeof attachments.$inferSelect;
export type Comment = typeof comments.$inferSelect;
export type Tag = typeof tags.$inferSelect;
export type NewTag = typeof tags.$inferInsert;
export type Taggable = typeof taggables.$inferSelect;
export type Contact = typeof contacts.$inferSelect;
export type NewsletterSubscription = typeof newsletterSubscriptions.$inferSelect;
export type NewNewsletterSubscription = typeof newsletterSubscriptions.$inferInsert;
export type UserProfiles = typeof userProfiles.$inferSelect;
export type NewUserProfiles = typeof userProfiles.$inferInsert;
export type Bank = typeof banks.$inferSelect;
export type NewBank = typeof banks.$inferInsert;
export type Position = typeof positions.$inferSelect;
export type NewPosition = typeof positions.$inferInsert;
export type Religion = typeof religions.$inferSelect;
export type NewReligion = typeof religions.$inferInsert;
export type School = typeof schools.$inferSelect;
export type NewSchool = typeof schools.$inferInsert;
export type Shift = typeof shifts.$inferSelect;
export type NewShift = typeof shifts.$inferInsert;
export type Stage = typeof stages.$inferSelect;
export type NewStage = typeof stages.$inferInsert;
export type Unit = typeof units.$inferSelect;
export type NewUnit = typeof units.$inferInsert;
export type Job = typeof jobs.$inferSelect;
export type NewJob = typeof jobs.$inferInsert;
export type JobApplicant = typeof jobApplicants.$inferSelect;
export type NewJobApplicant = typeof jobApplicants.$inferInsert;
export type Invoice = typeof invoices.$inferSelect;
export type InvoiceItem = typeof invoiceItems.$inferSelect;
export type InvoicePayment = typeof invoicePayments.$inferSelect;
export type Expense = typeof expenses.$inferSelect;
export type NewExpense = typeof expenses.$inferInsert;
export type Timesheet = typeof timesheets.$inferSelect;
export type NewTimesheet = typeof timesheets.$inferInsert;
export type LeaveRequest = typeof leaveRequests.$inferSelect;
export type NewLeaveRequest = typeof leaveRequests.$inferInsert;
export type Permission = typeof permissions.$inferSelect;
export type NewPermission = typeof permissions.$inferInsert;
export type RolePermission = typeof rolePermissions.$inferSelect;
export type NewRolePermission = typeof rolePermissions.$inferInsert;
export type UserPermission = typeof userPermissions.$inferSelect;
export type NewUserPermission = typeof userPermissions.$inferInsert;
export type Company = typeof companies.$inferSelect;
export type NewCompany = typeof companies.$inferInsert;
export type Employee = typeof employees.$inferSelect;
export type NewEmployee = typeof employees.$inferInsert;
export type ShiftSchedule = typeof shiftSchedules.$inferSelect;
export type Presence = typeof presences.$inferSelect;
export type NewPresence = typeof presences.$inferInsert;
export type EmployeeSalary = typeof employeeSalaries.$inferSelect;
export type PayrollBatch = typeof payrollBatches.$inferSelect;
export type NewPayrollBatch = typeof payrollBatches.$inferInsert;
export type Payroll = typeof payrolls.$inferSelect;
export type NewPayroll = typeof payrolls.$inferInsert;
export type PayrollPaymentLog = typeof payrollPaymentLogs.$inferSelect;
export type ProjectColumn = typeof projectColumns.$inferSelect;
export type NewProjectColumn = typeof projectColumns.$inferInsert;
export type TaskActivity = typeof taskActivities.$inferSelect;
export type NewTaskActivity = typeof taskActivities.$inferInsert;
export type Service = typeof services.$inferSelect;
export type NewService = typeof services.$inferInsert;
export type SalaryComponent = typeof salaryComponents.$inferSelect;
export type NewSalaryComponent = typeof salaryComponents.$inferInsert;
export type EmployeeSalaryComponent = typeof employeeSalaryComponents.$inferSelect;
export type NewEmployeeSalaryComponent = typeof employeeSalaryComponents.$inferInsert;
export type Device = typeof devices.$inferSelect;
export type NewDevice = typeof devices.$inferInsert;

export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;
export type Journal = typeof journals.$inferSelect;
export type NewJournal = typeof journals.$inferInsert;
export type JournalEntry = typeof journalEntries.$inferSelect;
export type NewJournalEntry = typeof journalEntries.$inferInsert;
export type JournalItem = typeof journalItems.$inferSelect;
export type NewJournalItem = typeof journalItems.$inferInsert;

export type Warehouse = typeof warehouses.$inferSelect;
export type NewWarehouse = typeof warehouses.$inferInsert;
export type Location = typeof locations.$inferSelect;
export type NewLocation = typeof locations.$inferInsert;
export type Product = typeof products.$inferSelect;
export type NewProduct = typeof products.$inferInsert;
export type ProductCategory = typeof productCategories.$inferSelect;
export type NewProductCategory = typeof productCategories.$inferInsert;
export type StockMove = typeof stockMoves.$inferSelect;
export type NewStockMove = typeof stockMoves.$inferInsert;
export type StockQuant = typeof stockQuants.$inferSelect;
export type NewStockQuant = typeof stockQuants.$inferInsert;

export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;
export type SalesOrder = typeof salesOrders.$inferSelect;
export type NewSalesOrder = typeof salesOrders.$inferInsert;
export type SalesOrderLine = typeof salesOrderLines.$inferSelect;
export type NewSalesOrderLine = typeof salesOrderLines.$inferInsert;

export type PurchaseOrder = typeof purchaseOrders.$inferSelect;
export type NewPurchaseOrder = typeof purchaseOrders.$inferInsert;
export type PurchaseOrderLine = typeof purchaseOrderLines.$inferSelect;
export type NewPurchaseOrderLine = typeof purchaseOrderLines.$inferInsert;

export type PurchaseRequisition = typeof purchaseRequisitions.$inferSelect;
export type NewPurchaseRequisition = typeof purchaseRequisitions.$inferInsert;
export type PurchaseRequisitionLine = typeof purchaseRequisitionLines.$inferSelect;
export type NewPurchaseRequisitionLine = typeof purchaseRequisitionLines.$inferInsert;

export type Announcement = typeof announcements.$inferSelect;
export type NewAnnouncement = typeof announcements.$inferInsert;
export type AnnouncementRecipient = typeof announcementRecipients.$inferSelect;
export type NewAnnouncementRecipient = typeof announcementRecipients.$inferInsert;

export type Schedule = typeof schedules.$inferSelect;
export type NewSchedule = typeof schedules.$inferInsert;

export type Category = typeof categories.$inferSelect;
export type NewCategory = typeof categories.$inferInsert;
export type Categorizable = typeof categorizables.$inferSelect;
export type NewCategorizable = typeof categorizables.$inferInsert;
